### ISSUE TITLE
Timing seems off

### ISSUE THREAD

**Issue by Offliner33** [jcoffa/SoG-Phase-Off#1]
I tried this script as I've been stuck on the course for a week now. It does not work as it should on my game. It fires to quickly some times and I don't get past the 2nd or 3rd barrel. Is this a problem on my end?

**Comment by jcoffa** [comment]
Hmm, great question! I mostly made this for fun on my end and have never tested it on somebody else's machine before. My best guess is that the loading time is longer (or shorter) for your computer and so it doesn't start the course on the correct frame. You can watch [the YouTube video in the README](https://youtu.be/9otD3gZgFZA) and see how long my loading time was and compare it to yours. If it's noticeably longer or shorter then that could definitely be the problem.

Don't suppose you'd be able to record yourself using the script and send it to me somehow? (an unlisted YouTube video, for example, you can use a free program [such as OBS](https://obsproject.com/) to record your screen as well). Otherwise you can try playing with the values on lines 54 and 68 to account for a longer or shorter loading time:

[Line 54](https://github.com/jcoffa/SoG-Phase-Off/blob/master/phase-off.ahk#L54):
```
	Frames(60)	; Wait for loading chamber entrance
```

[Lines 67-68](https://github.com/jcoffa/SoG-Phase-Off/blob/master/phase-off.ahk#L68):
```
	; Start the course with correct timing; a slight delay after the 1st spinning barrel points up
	Frames(143)
```

Playing around with the startup times should *theoretically* be the only thing you have to change in order to "sync up" the script to your game. And honestly you probably only have to edit the 2nd one I posted (the 143 frame one). It was really hard for me to dynamically account for the loading time of the game itself so I basically just kept playing with the values until I found ones that worked for me.

**Comment by Offliner33** [comment]
I appreciate that you made this. My loading time is a tiny bit longer. After changing around the Frames value on line 68, I managed to get it to work. Thank you for pointing me in the right direction. I had no previous experience with AutoHotKey but thanks to this I started to learn it.

Thank you for your help!

**Comment by jcoffa** [comment]
I'm so glad it ended up working for you! I never _really_ thought anybody else would find this script, so it makes me happy that someone did and got some use out of it too :smile: 

And yeah, autohotkey is one of those things that can be pretty powerful even with no programming experience! Once you start playing around with it you can start to notice all sorts of ways to use it.
